image: maven:3.6.3-jdk-11
stages: ["package","release","deploy"]

package:
    stage: package
    script:
        - mvn -DskipTests clean package 
    dependencies: []
    artifacts:
        paths:
            - target/*.jar
        when: on_success
        
docker-image:
    stage: release
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
deploy-phase:
    stage: deploy
        script:
            - mvn heroku:deploy
        when: on_success

