image: maven:3.6.3-jdk-11


stages: ["build","verify", "unit-test", "integration-test", "package","release"]

compile: 
    stage: build
    script:
        - mvn compile
spotbugs:
  stage: verify
  script:
     - mvn spotbugs:check
  artifacts:
    paths:
        - target/spotbugsXml.xml

# Linter
checkstyle:
  stage: verify
  script:
      - mvn -Dmaven.javadoc.skip=true checkstyle:check
  allow_failure: true
  artifacts:
      paths:
        - target/checkstyle-result.xml

unit-test:
    stage: unit-test
    script:
        - mvn test
integration-test:
    stage: integration-test
    script:
        - mvn failsafe:integration-test
        
package:
    stage: package
    script:
        - mvn -DskipTests clean package 
    dependencies: []
    artifacts:
        paths:
            - target/*.jar
        when: on_success
docker-image:
    stage: release
    image: docker:stable
    services:
        - docker:dind
    dependencies: []
    script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE_NAME
    - docker push $CONTAINER_IMAGE_NAME


