image: maven:3.6.3-jdk-11
stages: ["package","release" , "deploy"]
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

package:
    stage: package
    script:
        - mvn -DskipTests clean package 
    dependencies: []
    artifacts:
        paths:
            - target/*.jar
        when: on_success
        
docker-image:
    stage: release
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - 'which ssh-agent || ( apt-get update -qq && apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600  ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://$DEPLOY_IP
    script:
        - chmod +x script_deploy_step.sh
        - bash script_deploy_step.sh
