image: maven:3.6.3-jdk-11
stages: ["deploy"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - chmod 400 $SSH_PRIVATE_KEY
        - 'which ssh-agent || ( apt-get update -qq && apt-get install openssh-client -qq )'
        - eval $(ssh-agent -s)
        - ssh-add $SSH_PRIVATE_KEY
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'        
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://52.164.218.129
    script:
        - chmod +x .gitlab-ci-deploy-staging.sh
        - bash .gitlab-ci-deploy-staging.sh
