image: maven:3.6.3-jdk-11
stages: ["deploy"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - 'which ssh-agent || ( apt-get update -qq && apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600  ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'   
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://52.164.218.129
    script:
        - chmod +x script_deploy_step.sh
        - bash script_deploy_step.sh
