image: maven:3.6.3-jdk-11
stages: ["package","release" , "deploy"]
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

package:
    stage: package
    script:
        - mvn -DskipTests clean package 
    dependencies: []
    artifacts:
        paths:
            - target/*.jar
        when: on_success
        
docker-image:
    stage: release
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -qq && apt-get install openssh-client -qq )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'        
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://$DEPLOY_IP
    script:
        - ssh azureuser@52.164.218.129 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker rm --force pipeline || true && docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && docker run -d --restart on-failure:5 --name pipeline $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && exit"