image: maven:3.6.3-jdk-11
stages: ["release", "deploy"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  
docker-image:
    stage: release
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )' 
        - eval $(ssh-agent -s) 
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
        - mkdir -p ~/.ssh - chmod 700 ~/.ssh 
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://13.73.147.152
    script:
        - ssh -o PreferredAuthentications=publickey azureuser@13.73.147.152 "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker rm --force pipeline || true && docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && docker run -d --restart on-failure:5 --name pipeline $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && exit"

