image: maven:3.6.3-jdk-11

stages: ["build", "unit-test", "integration-test"]

compile: 
    stage: build
    script:
        - mvn compile

unit-test:
    stage: unit-test
    script:
        - mvn test
integration-test:
    stage: integration-test
    script:
        - mvn failsafe:integration-test
