image: maven:3.6.3-jdk-11
stages: ["deploy"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

deploy-stage:
    stage: deploy
    image: debian:stable-slim
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )' 
        - eval $(ssh-agent -s) 
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
        - mkdir -p ~/.ssh - chmod 700 ~/.ssh 
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    cache: {}
    dependencies: []
    environment:
        name: script_deploy_step
        url: https://13.73.147.152
    script:
        - ssh -o PreferredAuthentications=publickey azureuser@13.73.147.152 "sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && sudo docker rm --force pipeline-1.0-SNAPSHOT || true && sudo docker pull $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && sudo docker run -d --restart on-failure:5 --name pipeline-1.0-SNAPSHOT $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME && exit"       
